name: CI
run-name: CI - {{ env.IMAGE_NAME }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: pyui
  IMAGE_TAG: v1
  DOCKER_ACCOUNT: d4v5he

jobs:
  Setup:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python
        run: |
          sudo yum update -y
          sudo yum install python3 -y
          sudo yum install -y python3-pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir boto3 flask

  docker-build-push:
    runs-on: self-hosted
    needs: Setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          sudo yum install -y docker
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER
          newgrp docker
          sudo chmod 666 /var/run/docker.sock

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t {{ env.DOCKER_ACCOUNT }}/{{ env.IMAGE_NAME }}:{{ env.IMAGE_TAG }} ./app

      - name: Push Docker image
        run: docker push {{ env.DOCKER_ACCOUNT }}/{{ env.IMAGE_NAME }}:{{ env.IMAGE_TAG }}
