name: CI
run-name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/cicd.yaml
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir boto3 flask


  docker-build-push:
    runs-on: self-hosted
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t pyui:v1 ./app
          docker tag pyui:v1 d4v5he/pyui:v1

      - name: Push Docker image
        run: docker push d4v5he/pyui:v1
