name: Install Minikube on EC2

on:
  workflow_dispatch:
    inputs:
      EC2_IP:
        description: "The IP address of the Minikube EC2 instance"
        required: true

jobs:
  install-minikube:
    runs-on: self-hosted

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Minikube on EC2
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ inputs.EC2_IP }}
        username: ec2-user
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          sudo yum update -y
          sudo yum install -y docker
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker ec2-user && newgrp docker
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube version
          minikube start --driver=docker
